### ISSUE TITLE
【】音声再生部分の調整を実装する

### ISSUE THREAD

**Issue by nakamurakyo** [nakamurakyo/jiminy#16]
VolumeDown ▲▲△△△VolumeUp

**Comment by mafuyuk** [comment]
http://fontawesome.io/icon/volume-down/
http://fontawesome.io/icon/volume-up/
http://fontawesome.io/icon/play/

**Comment by nakamurakyo** [comment]
こちら、該当の対応を含んだプルリクをマージしたのでクローズします
